debug: 0
Profile_URL: https://api.mojang.com/profiles/minecraft
online_UUID_Check: true
HTTPConnectTimeout: 15000
HTTPReadTimeout: 15000
worldRestrict: true
fill-emptier-first: false
keep-priority-sorted: false
proximity: 0
proximity-exceptions:
  069a79f4-44e9-4726-a5be-fca90e38aaf5:
    exampleNetwork: 20
  61699b2e-d327-4a01-9f1e-0ea8c3f06bc6:
    anotherNetworkExample: 150
inventoryBlocks:
  DEPOSIT:
  - chest
  - furnace
  - trapped_chest
  - hopper
  WITHDRAW:
  - chest
  - trapped_chest
  SORT:
  - dispenser
  - chest
  - trapped_chest
  - hopper
  - dropper
customGroups:
  MINECARTS:
  - minecart
  - chest_minecart
  - furnace_minecart
  - tnt_minecart
  - hopper_minecart
  - command_block_minecart
  MINERALS:
  - granite
  - polished_granite
  - diorite
  - polished_diorite
  - andesite
  - polished_andesite
  - gravel
  - flint
  WOOD:
  - oak_planks
  - spruce_planks
  - birch_planks
  - jungle_planks
  - acacia_planks
  - dark_oak_planks
  - oak_log
  - oak_log
  - spruce_log
  - birch_log
  - oak_leaves
  - spruce_leaves
  - birch_leaves
  - jungle_leaves
  - glass
  - acacia_leaves
  - dark_oak_leaves
  - acacia_log
  - spruce_log
  SANDANDFRIENDS:
  - sand
  - red_sand
  - sandstone
  - chiseled_sandstone
  - cut_sandstone
  - white_stained_glass
  - orange_stained_glass
  - magenta_stained_glass
  - light_blue_stained_glass
  - yellow_stained_glass
  - lime_stained_glass
  - pink_stained_glass
  - gray_stained_glass
  - light_gray_stained_glass
  - cyan_stained_glass
  - purple_stained_glass
  - blue_stained_glass
  - brown_stained_glass
  - green_stained_glass
  - red_stained_glass
  - black_stained_glass
  NETHER:
  - netherrack
  - soul_sand
  - glowstone
  - nether_bricks
  - nether_brick_fence
  - nether_brick_stairs
  - nether_wart
  - redstone_block
  - nether_quartz_ore
  - quartz_block
  - quartz_stairs
  - glowstone_dust
  - nether_wart
  - nether_brick
  - quartz
  COLORS:
  - white_wool
  - orange_wool
  - magenta_wool
  - light_blue_wool
  - yellow_wool
  - lime_wool
  - pink_wool
  - gray_wool
  - light_gray_wool
  - cyan_wool
  - purple_wool
  - blue_wool
  - brown_wool
  - green_wool
  - red_wool
  - black_wool
  - dandelion
  - poppy
  - blue_orchid
  - allium
  - azure_bluet
  - red_tulip
  - orange_tulip
  - white_tulip
  - pink_tulip
  - oxeye_daisy
  - white_terracotta
  - orange_terracotta
  - magenta_terracotta
  - light_blue_terracotta
  - yellow_terracotta
  - lime_terracotta
  - pink_terracotta
  - gray_terracotta
  - light_gray_terracotta
  - cyan_terracotta
  - purple_terracotta
  - blue_terracotta
  - brown_terracotta
  - green_terracotta
  - red_terracotta
  - black_terracotta
  - white_stained_glass_pane
  - orange_stained_glass_pane
  - magenta_stained_glass_pane
  - light_blue_stained_glass_pane
  - yellow_stained_glass_pane
  - lime_stained_glass_pane
  - pink_stained_glass_pane
  - gray_stained_glass_pane
  - light_gray_stained_glass_pane
  - cyan_stained_glass_pane
  - purple_stained_glass_pane
  - blue_stained_glass_pane
  - brown_stained_glass_pane
  - green_stained_glass_pane
  - red_stained_glass_pane
  - black_stained_glass_pane
  - white_carpet
  - orange_carpet
  - magenta_carpet
  - light_blue_carpet
  - yellow_carpet
  - lime_carpet
  - pink_carpet
  - gray_carpet
  - light_gray_carpet
  - cyan_carpet
  - purple_carpet
  - blue_carpet
  - brown_carpet
  - green_carpet
  - red_carpet
  - black_carpet
  - sunflower
  - lilac
  - tall_grass
  - large_fern
  - rose_bush
  - peony
  - ink_sac
  - rose_red
  - cactus_green
  - cocoa_beans
  - lapis_lazuli
  - purple_dye
  - cyan_dye
  - light_gray_dye
  - gray_dye
  - pink_dye
  - lime_dye
  - dandelion_yellow
  - light_blue_dye
  - magenta_dye
  - orange_dye
  - bone_meal
  MAGIC:
  - paper
  - book
  - potion
  - glass_bottle
  - fermented_spider_eye
  - blaze_powder
  - magma_cream
  - brewing_stand
  - cauldron
  - ender_eye
  - glistering_melon_slice
  - experience_bottle
  - fire_charge
  - writable_book
  - written_book
  - nether_star
  - enchanted_book
  - dragon_breath
  - splash_potion
  - spectral_arrow
  - tipped_arrow
  - lingering_potion
  DROPS:
  - string
  - feather
  - gunpowder
  - bone
  - ender_pearl
  - blaze_rod
  - ghast_tear
  - spider_eye
  - fermented_spider_eye
  - rabbit_hide
  TOOLSARMOR:
  - wooden_hoe
  - stone_hoe
  - iron_hoe
  - diamond_hoe
  - golden_hoe
  - iron_ingot
  - iron_pickaxe
  - iron_axe
  - iron_axe
  - bow
  - arrow
  - iron_sword
  - wooden_sword
  - wooden_shovel
  - wooden_pickaxe
  - wooden_axe
  - stone_sword
  - stone_shovel
  - stone_pickaxe
  - stone_axe
  - diamond_sword
  - diamond_shovel
  - diamond_pickaxe
  - diamond_axe
  - golden_sword
  - golden_shovel
  - golden_pickaxe
  - golden_axe
  - leather_helmet
  - leather_chestplate
  - leather_leggings
  - leather_boots
  - chainmail_helmet
  - chainmail_chestplate
  - chainmail_leggings
  - chainmail_boots
  - iron_helmet
  - iron_chestplate
  - iron_leggings
  - iron_boots
  - diamond_helmet
  - diamond_leggings
  - diamond_boots
  - golden_helmet
  - golden_chestplate
  - golden_leggings
  - golden_boots
  - bucket
  - water_bucket
  - lava_bucket
  - oak_boat
  - compass
  - fishing_rod
  - clock
  - shears
  - carrot_on_a_stick
  - shield
  - elytra
  - spruce_boat
  - birch_boat
  - jungle_boat
  - acacia_boat
  - dark_oak_boat
  - totem_of_undying
  FOOD:
  - cake
  - apple
  - mushroom_stew
  - bread
  - porkchop
  - cooked_porkchop
  - golden_apple
  - enchanted_golden_apple
  - cod
  - salmon
  - tropical_fish
  - pufferfish
  - cooked_cod
  - cooked_salmon
  - cake
  - cookie
  - melon
  - beef
  - cooked_beef
  - chicken
  - rotten_flesh
  - carrot
  - potato
  - baked_potato
  - golden_carrot
  - rabbit
  - cooked_rabbit
  - rabbit_stew
  - mutton
  - cooked_mutton
  AGRICULTURE:
  - egg
  - oak_sapling
  - spruce_sapling
  - birch_sapling
  - jungle_sapling
  - acacia_sapling
  - dark_oak_sapling
  - cactus
  - sugar_cane
  - carved_pumpkin
  - melon
  - lily_pad
  - cocoa
  - carrots
  - potatoes
  - hay_block
  - wheat_seeds
  - wheat
  - leather
  - milk_bucket
  - sugar_cane
  - sugar
  - pumpkin_seeds
  - melon_seeds
  VALUABLES:
  - gold_ore
  - iron_ore
  - coal_ore
  - lapis_ore
  - gold_block
  - iron_block
  - cobweb
  - diamond_ore
  - diamond_block
  - redstone_ore
  - emerald_ore
  - emerald_block
  - coal_block
  - coal
  - charcoal
  - diamond
  - iron_ingot
  - gold_ingot
  - iron_sword
  - gold_nugget
  - emerald
  - iron_nugget
  ELECTRONICS:
  - piston
  - powered_rail
  - detector_rail
  - sticky_piston
  - rail
  - light_weighted_pressure_plate
  - heavy_weighted_pressure_plate
  - comparator
  - daylight_detector
  - redstone_block
  - hopper
  - dropper
  - redstone
  - repeater
  - comparator
  BUILDINGMATS:
  - stone_slab
  - sandstone_slab
  - petrified_oak_slab
  - cobblestone_slab
  - brick_slab
  - stone_brick_slab
  - nether_brick_slab
  - quartz_slab
  - bricks
  - bookshelf
  - mossy_cobblestone
  - torch
  - oak_stairs
  - crafting_table
  - furnace
  - sign
  - oak_door
  - ladder
  - cobblestone_stairs
  - wall_sign
  - lever
  - stone_pressure_plate
  - iron_door
  - oak_pressure_plate
  - redstone_torch
  - stone_button
  - snow
  - ice
  - snow_block
  - clay
  - oak_fence
  - oak_trapdoor
  - stone_bricks
  - mossy_stone_bricks
  - cracked_stone_bricks
  - iron_bars
  - glass_pane
  - oak_fence_gate
  - brick_stairs
  - stone_brick_stairs
  - mycelium
  - redstone_lamp
  - oak_slab
  - spruce_slab
  - birch_slab
  - jungle_slab
  - acacia_slab
  - dark_oak_slab
  - sandstone_stairs
  - spruce_stairs
  - birch_stairs
  - jungle_stairs
  - beacon
  - cobblestone_wall
  - flower_pot
  - oak_button
  - anvil
  - acacia_stairs
  - dark_oak_stairs
  - iron_trapdoor
  - spruce_fence_gate
  - birch_fence_gate
  - jungle_fence_gate
  - dark_oak_fence_gate
  - acacia_fence_gate
  - spruce_fence
  - birch_fence
  - jungle_fence
  - dark_oak_fence
  - acacia_fence
  - spruce_door
  - birch_door
  - jungle_door
  - acacia_door
  - dark_oak_door
  - stick
  - sign
  - oak_door
  - iron_door
  - brick
  - clay_ball
  - spruce_door
  - birch_door
  - jungle_door
  - acacia_door
  - dark_oak_door
